name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - uses: nrwl/nx-set-shas@v3
      - run: pnpm install

      - run: pnpm nx format:check
      - run: pnpm nx affected -t lint --parallel=3
      - run: pnpm nx affected -t test --parallel=3 --configuration=ci
      - run: pnpm nx affected -t build --parallel=3
